Eurachacha/hanmogeum

.eslintrc
src/components/common/Button.tsx
src/index.css

`feat/common-button-component` -> `dev`
- 공용 버튼 컴포넌트 생성
- rem 사용을 위한 html 태그 font-size 62.5% 설정
#10 #11  
- width는 100%로 설정해두었기 때문에 부모의 width를 조절하면 됩니다.
- margin은 0으로 설정해두었기 때문에 부모 요소에서 조절하면 됩니다.
- disabled 여부는 옵셔널입니다. 전달하지 않는 경우 default 값은 false로 설정됩니다.
- onClick속성은 본 버튼을 감싸는 태그에 전달하면 됩니다.
- 버튼의 type은 submit이 기본이므로 따로 전달받지 않도록 설정했습니다.
form 태그의 onSubmit에 함수를 전달하면 됩니다.
- Link태그를 사용하는 경우 본 버튼을 Link태그로 감싸면 작동합니다. 
Link태그의 width 값을 변경하려면 `display: block` 으로 설정해줘야 합니다.

feat(@/components/Button.tsx): 공용 버튼 컴포넌트 생성 (#10)

---

src/components/common/Input.tsx
src/types/input.ts

공용으로 사용 수 있게 Input 컴포넌트를 구현하였습니다.
feat/input-component -> dev
- 공용으로 사용할 Input 컴포넌트 구현
- 공용 컴포넌트이므로 바로 사용하지는 않았으나, 임의로 메인페이지에 넣어본 스크린샷 입니다.
#5

feat(@/src/common, @/types): Input 컴포넌트 추가(#9)

---

src/index.css

기본 폰트 크기를 16px 기준으로  전역으로 적용하기 위해 추가하였습니다.
feat/body-default-fontsize -> dev
- body 스타일에 `font-size: 1.6rem` 추가
#11

design(@): body태그 속성 기본폰트 크기 1.6rem 설정(#16)

---

src/components/common/category/CategoryButton.tsx

카테고리 페이지에서 사용할 버튼 컴포넌트를 생성했습니다.
사용하는 컴포넌트 또는 페이지에서 props를 넘겨줍니다.
`feat/category-button-component` -> `dev`
- active와 default 두 가지 상태로 설정하였습니다.
- 버튼을 클릭하면 해당 버튼의 상태가 변경됩니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/2f6d539e-12de-4bca-9de4-255d1d3fbb37
#5 #12
- 클릭 시 주소 변경 로직을 추가할 예정입니다. 
- 파일 위치 `components/common/category`에서 `components/category`로 변경이 필요합니다.

feat(@/components/category): 카테고리 버튼 생성(#12)

---

src/components/common/Button.tsx

feat/common-button-component -> dev
- 코드 컨벤션에 따라 interface를 import문 하위로 이동

chore(Button.tsx): interface를 import문 아래로 이동 (#32)

---

src/components/product/ProductItemLabel.tsx

ex) feat/product-item-component -> dev
상품 아이템 컴포넌트 상단 라벨에 props 속성을 추가하였습니다.
사용하는 곳에서 padding과 margin 값도 조정할 수 있게 수정하여
컴포넌트를 더욱 범용적으로 사용할 수 있도록 하였습니다.
ex) #21

fix(@/components): 상품 아이템 라벨 props 속성 추가(#21)

---

package.json
src/App.tsx
src/constants/localstorageKeys.ts
src/containers/LoginContainer/LoginContainer.tsx
src/pages/LoginPage.tsx
src/recoil/atoms/loggedInUserState.ts
src/recoil/selectors/getUserIdState.ts

feat/login -> dev
-   recoil-persist 설치
-  사용자 정보 상태관리 atom, selector 추가
-  로그인 페이지 구현

feat(Login): 로그인 페이지 구현

---

package-lock.json
src/components/product/ProductItem.tsx
src/components/product/ProductItemList.tsx

상품 아이템과 해당 아이템 목록 컴포넌트를 구현했습니다.
상품 아이템에 대한 데이터를 ProductItemList에서 get 하였습니다.
ex) feat/product-item-component -> dev
- 상품 아이템과 해당 아이템 리스트를 보여주는 컴포넌트를 생성했습니다. 
ex) #21
ProductItemList에서 get 해온 데이터를 ProductListPage에서 get 해오는 방식으로 수정할 계획입니다.

feat(product): 상품 아이템과 아이템 리스트 구현(#21)

---

.eslintrc
src/apis/services/cart.ts
src/apis/services/orders.ts
src/components/common/Button.tsx
src/components/orderCheckout/FormInput.tsx
src/components/orderCheckout/Info.tsx
src/components/orderCheckout/OrderItem.tsx
src/containers/orderCheckout/InfoContainer.tsx
src/containers/orderCheckout/OrderListContainer.tsx
src/containers/orderCheckout/ShippingInfoContainer.tsx
src/pages/OrderCheckoutPage.tsx
src/types/cart.ts
src/types/orders.ts

- 주문할 상품 정보 출력
- 주문자 정보 출력 (현재 로그인된 유저 정보)
- 배송 정보 input 생성
#84
우측 금액안내 부분은 구현예정입니다.

feat(order-checkout): 주문하기페이지 좌측 기본 마크업 완료 (#84)

---

package-lock.json
package.json
src/containers/SignUpContainer/SignUpContainer.tsx

feat/signup-map-api -> dev
- 회원가입 주소찾기 버튼 클릭 시 카카오 우편번호 서비스 연동을 추가하였습니다.
- react-daum-postcode 패키지를 사용하였습니다.
#38

feat(SignUp): 카카오 우편번호 서비스 연동 (#90)

---

src/hooks/useQueryParams.tsx

ex) feat/product-item-component -> dev
카테고리 클릭 시 쿼리스트링에 반영되는 로직 커스텀훅을 만들었습니다.
같은 카테고리 내 쿼리스트링은 띄어쓰기로 저장하였습니다. 띄어쓰기로 나눠진 쿼리스트링은 주소에서는 +로 표시됩니다. 
쿼리스트링을 이용해 데이터를 필터링할 때 띄어쓰기를 기준으로 배열을 나눠 작업해야 합니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/fe5ca330-d180-48a0-bf85-48567b463683
ex) #87

feat(hooks): 쿼리스트링 저장하는 커스터 훅 추가(#87)

---

src/components/mypage/ContainerHeader..tsx
src/components/mypage/NavigationMenu.tsx
src/components/mypage/OrderItem.tsx
src/components/mypage/OrderItemContentsText.tsx
src/containers/mypageContainer/MypageLayoutContainer.tsx

feat/mypage-common-component -> dev
- 네비게이션 메뉴 컴포넌트 구현
- 본문의 헤더 컴포넌트 구현
- 주문 아이템 컴포넌트 구현
- 공통 레이아웃 컨테이너 구현
#109

feat(mypage): 마이페이지에서 공통 컴포넌트, 컨테이너 구현

---

src/apis/instance.ts
src/containers/LoginContainer/LoginContainer.tsx

feat/refresh -> dev
로그인 시 refreshToken을 로컬스토리지에 저장하도록 했습니다.
axios 응답 interceptor에서 토큰 만료 시 refreshToken으로 연장 처리합니다.

feat(/apis): 토큰 만료 시 자동 로그인 연장 처리 (#116)

---

src/App.tsx
src/apis/services/code.ts
src/apis/services/mypage.ts
src/components/common/Header.tsx
src/components/mypage/OrderItem.tsx
src/containers/mypageContainer/MyOrderListContainer.tsx
src/containers/mypageContainer/MypageLayoutContainer.tsx
src/main.tsx
src/pages/MyOrderListPage.tsx
src/recoil/atoms/codeState.ts
src/types/code.ts
src/types/myPage.ts
src/utils/getDate.ts
src/utils/truncateString.ts

feat/mypage-orderList -> dev
- truncateString 함수 추가
제목 썸네일 등을 표시할 때, 제한 길이를 초과하는 경우 ...로 표시하는 유틸리티 함수를 추가하였습니다.
- getDate 클래스 추가
백엔드의 date설정을 Date객체로 변환하고, 사용가자 원하는 메서드를 받을 수 있도록 클래스를 구현하였습니다.
- 코드목록 상태관리 추가
코드목록은 자주 바뀌지 않는 데이터이기 때문에, 최상위 App 컴포넌트에서 한번만 불러오도록 코드를 수정하였습니다.
- 주문 목록 페이지 구현
주문 목록 페이지 컨테이너와 컴포넌트를 구현하였습니다.
- 코드 컨벤션 맞춤
export 부분의 위치를 style 전으로 맞추었습니다.
-  헤더 마이페이지 경로 수정 
NavLink active효과를 위해, 헤더의 마이페이지 경로를 주문내역 경로로 이동하도록 수정하였습니다.
#111, #109
관련이슈가 #111 이나, 실수로 #109에 이슈 태그를 달았습니다.

feat(mypage/orderList) 주문 내역 페이지 구현

---

src/apis/services/products.ts

ex) feat/product-list -> dev
정렬과 필터 작업을 위한 api 함수를 생성했습니다.
모든 데이터를 불러오는 기존 함수(productsApi)에 필터링된 데이터를 불러올 수 있는 함수(searchProducts)를 추가했습니다. 
#128

feat(/apis): 정렬&필터 작업을 위한 api 함수 생성(#128)

---

src/components/cart/CartItem.tsx
src/containers/cart/CartItemContainer.tsx
src/containers/cart/CartItemListContainer.tsx
src/containers/cart/CartPriceContainer.tsx
src/pages/CartPage.tsx

- 로그인 여부에 따른 장바구니 금액안내 기능 구현
- 구매하기 버튼 스타일 수정
#102
현재는 api 요청시 받는 cost 값을 활용하고 있지 않고, 아이템정보들만으로 계산하여 출력하고 있습니다.

feat(cart): 로그인 여부에 따른 장바구니 금액안내 기능 구현 (#125)

---

src/App.tsx
src/components/common/Header.tsx
src/containers/mypageContainer/MyOrderListContainer.tsx
src/recoil/atoms/codeState.ts
src/recoil/selectors/codeSelector.ts
src/recoil/selectors/loggedInUserSelector.ts
src/types/code.ts

feat/header-category-path -> dev
- 타입 명칭 수정
nested 구조 사용을 고려한 기존 code 명칭을 수정하였습니다.
기존 코드 관련된 부분도 수정하였습니다.
- `getProductCategoryValueByCode` 코드 selector추가
value를 기준으로 code를 가져오는 Selector를 추가하였습니다.
- 카테고리 쿼리스트링 코드로 수정
헤더에 카테고리 버튼 클릭 시 쿼리스트링이 코드가 되게 수정하였습니다.
getProductCategoryValueByCode Selector를 사용하였습니다.
#121

fix(header): 카테고리 쿼리스트링 코드로 수정

---

src/components/mypage/OrderDetailInfo.tsx
src/containers/mypageContainer/MyOrderDetailContainer.tsx
src/containers/mypageContainer/MyOrderListContainer.tsx
src/pages/MyOrderDetailPage.tsx
src/pages/MyOrderListPage.tsx
src/recoil/selectors/loggedInUserSelector.ts
src/utils/getPriceFormat.ts

feat/mypage-orderdetail -> dev
- 주문 상세페이지 구현
- 유틸리티 함수인 가격 포멧팅 함수 구현
- 사용자 이름 가져오는 selector 추가
#147

feat(OrderDetail): 주문 상세페이지 구현 (#147)

---

src/components/cart/CartItem.tsx

ex) feat/cart -> dev
로그인상태로 초기 접속시 재고가 부족하면 재고만큼 input에 반영하고 수량 수정 요청을 하도록 구현했습니다.

feat(cart): [로그인] 재고부족시 재고만큼 수량 update (#154)

---

src/components/cart/CartItem.tsx

장바구니 수량 조절 시 재고가 0개인 경우 0미만으로 내려가는 버그를 수정했습니다.

feat(cart): 수량조절시 0 미만 제한 (#186)

---

src/components/common/Header.tsx

feat/header-cart-counting -> dev
- recoil에서 관리중인 cartState 배열의 길이에 따라 장바구니의 개 수 가 표시되도록 수정하였습니다.
#178

fix(header): 헤더 장바구니 개수 출력 (#178)

---

src/components/mypage/OrderDetailInfo.tsx
src/containers/mypageContainer/MyOrderListContainer.tsx
src/types/myPage.ts

feat/mypage-OrderDetailInfo-fix -> dev
- 구매하기 페이지의 구매 정보와, 구매 내역에서 보여주는 구매자 정보가 맞지 않아 수정하였습니다.
#176

fix(OrderDetailInfo): 주문자 정보 수정 (#176)

---

src/components/common/Modal.tsx

- `\n`문자열로 split후 map함수를 사용해 줄바꿈텍스트를 넣을 수 있습니다.
- targetString optional prop에 전달되는 문자열은 강조처리됩니다.

chore(Modal): 줄바꿈, 강조텍스트 구현 (#220)

---

src/pages/ProductDetailPage.tsx

- 비로그인 유저가 바로구매 클릭시 로그인 의사를 묻습니다.
- 로그인유저가 바로구매 클릭 시 구매할 상품 정보를 모달로 확인하고 구매할 수 있도록 합니다.
[비로그인 유저] 구매하기 클릭
[로그인 유저] 구매하기 클릭

feat(상품상세): 바로구매 기능 구현 (#217)

---

src/components/product/productlist/CategoryList.tsx
src/constants/category.ts

- 상품 목록 리스트 카테고리에서 pack 데이터 제외하고 출력하였습니다. 
- 기존 각각 다른 컴포넌트를 사용하던 카테고리 리스트를 디카페인-토글 영역까지 포함할 수 있는 코드로 수정하였습니다. 
- 상품 목록 리스트 카테고리 영문으로 출력되던 타이틀 데이터 한글로 수정했습니다. 타이틀 한글명을 상수화하여 값을 불러왔습니다. 
- 타이틀에 맞는 서브 타이틀 데이터를 추가하였습니다. 서브타이틀을 상수화하여 값을 불러왔습니다. 
#138 #182

feat(ProductList): 상품목록 카테고리에서 pack 제외(#138)

---

src/components/product/productlist/CategoryButtonList.tsx

카테고리 버튼 리스트에 받아오는 배열 데이터의 타입을 수정했습니다.
직접 지정한 타입에서 services/code에서 타입 정의한 CodeWithSub을 사용했습니다.
#138

fix(ProductList):카테고리 버튼 리스트 타입 수정(#138)

---

src/components/common/Header.tsx

feat/logout-check-cart -> dev
- 로그아웃 시 cartCheckedItemState 초기화 하는 로직을 추가하였습니다.
ex) #111

fix(logout): 로그아웃 시 cartCheckedItemState 초기화(#211)

---

src/containers/cart/CartPriceContainer.tsx

- 선택상품금액이 0원인 경우 구매하기 버튼이 비활성화되도록 처리했습니다.
#201

feat(cart): 선택상품금액이 0원이면 구매하기 버튼 비활성화 (#134)

---

src/components/cart/CartItem.tsx
src/containers/cart/CartItemContainer.tsx
src/containers/cart/CartItemListContainer.tsx
src/pages/CartPage.tsx

수량이 0이되면 자동으로 체크박스 해체됩니다.
수량이 0인 상품의 체크박스를 다시 체크하면 자동으로 수량이 1 증가합니다.
재고가 0개인 상품은 체크박스가 비활성화됩니다.

feat(cart): 아이템수량이 0이될때 체크박스 상태 변화 구현(#242)

---

src/pages/ProductDetailPage.tsx

상품재고가 0개인 경우 수량인풋을 0으로 설정하도록 했습니다.

feat(상품상세): 재고가 0인 경우 수량인풋 0으로 설정(#252)

---

src/containers/cart/CartItemListContainer.tsx

로그인 상태에서도 헤더에서 장바구니 개수를 불러오기 위해
장바구니 DB의 item 개수가 바뀌면 cartStorage에 DB상태 반영하도록 했습니다.
헤더에 정확한 수량 반영을 위해 품절된 상품(재고 0개)을 제외한 개수를 반영하도록 작업할 예정입니다.

feat(cart): DB장바구니개수 변경시 cartStorage에 반영(#255)

---

src/components/common/Header.tsx

헤더 장바구니 수량을 반영할 때 품절된 상품은 제외한 개수를 반영하도록 수정했습니다.(filter)

feat(header): 헤더장바구니수량 품절상품제외 후 반영(#257)

---

src/containers/cart/CartItemContainer.tsx

- 단일상품삭제 시 남아있는 상품의 수량이 삭제된 상품 수량값으로 변경되고, 무한렌더링이 일어나는 문제를 해결했습니다.
- CartItem컴포넌트의 key값을 product_id를 반영하도록 수정했습니다.

fix(cart): 단일상품삭제시 수량변경및 무한렌더링해결(#260)

---

src/apis/services/orders.ts

- 구매하기API 요청함수에서 배송상태를 OS030(배송준비중)으로 설정되도록 수정했습니다.

feat(order): 구매요청시 배송준비중을 기본state로 전달(#254)

---

src/containers/product/ProductSortContainer.tsx

상품 목록 카테고리 버튼 클릭 시 쿼리스트링을 받아와 데이터를 요청하는 코드를 추가하였습니다.
교집합: 네비게이션 카테고리와 그 하위(디카페인, 종류, 맛, 상황) 카테고리
합집합: 종류, 맛, 상황 하위 카테고리 간
https://github.com/Eurachacha/hanmogeum/assets/117130358/13305eda-7443-4e1a-8d23-845b4271575b
#87

feat(ProductList): 상품 목록 카테고리 클릭 시 데이터 요청(#87)

---

src/components/product/productlist/ProductSortButtons.tsx
src/containers/product/ProductSortContainer.tsx

ex) feat/login -> dev
상품 정렬 버튼이 모여있는 컴포넌트에 보내는 데이터를 수정했습니다.
기존에는 products 정보 전체를 보내는 방식이었으나, 
정렬 버튼 클릭 시 쿼리스트링을 변경하고 쿼리스트링이 변경되면 데이터 요청 보내는 코드를 상위 컴포넌트인 ProductSortContainer에 추가함에 따라 products의 length 속성만 props로 넘겨주는 방식으로 변경했습니다.
#266

fix(ProductList): 상품 정렬 버튼 컴포넌트에 보내는 데이터 수정(#266)

---

src/components/product/productlist/CategoryButton.tsx

카테고리 버튼에 disabled 속성을 옵셔널로 추가했습니다. 
disabled 속성을 추가한 카테고리 버튼은 클릭이 안 되고 focus가 잡히지 않습니다. 
사용 예시
```jsx
<CategoryButton
key={index}
variant="default"
onClick={() => toggleFilter(`${category.code}`)}
disabled
>
버튼
</CategoryButton>
```
#216

fix(ProductList): 카테고리버튼 disabled 속성 추가(#216)

---

src/containers/cart/CartItemContainer.tsx
src/containers/cart/CartItemListContainer.tsx

장바구니에 상품이 없는 경우 EmptyMessage 컴포넌트를 출력합니다.
#271

feat(cart): 상품이 없을 때 메시지 출력(#126)

---

src/containers/orderCheckout/OrderInfoContainer.tsx
src/pages/OrderCheckoutPage.tsx

구매하기페이지 접근 시 아이템이 없는 경우 홈으로 이동하도록 구현했습니다.
replace: true로 설정하여 뒤로가기하더라도 구매하기페이지로 다시 돌아오지 않도록 했습니다.

feat(구매하기): 접속시 아이템이 없는경우 홈으로 이동(#126)

---

src/containers/orderCheckout/OrderInfoContainer.tsx
src/containers/orderCheckout/OrderListContainer.tsx
src/containers/orderCheckout/OrderPriceContainer.tsx
src/pages/OrderCheckoutPage.tsx
src/pages/ProductDetailPage.tsx
src/types/orders.ts

- 바로구매 클릭시 navigate함수의 state에 아이템정보와 구매수량을 전달합니다.
- 구매하기페이지에서 useLocation을 사용해 state값을 불러옵니다.
- state값이 존재하는 경우 해당 구매정보만 보여주고, 그렇지않으면 카트정보를 불러옵니다.

feat(상품상세): 바로구매기능 구현(#204)

---

src/components/product/productlist/CategoryButton.tsx
src/components/product/productlist/CategoryButtonList.tsx

카테고리 버튼 클릭 시 활성화된 버튼의 색상을 변경하는 코드를 추가했습니다.
useLocation 객체의 search 메서드를 통해 쿼리스트링을 저장하고, 저장한 쿼리스트링에 클릭한 버튼의 code가 포함되어 있으면 active 스타일을 적용하였습니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/b4f1becb-92f2-48ac-a0db-41c835b67fc2
#87  #210

feat(ProductList): 필터 버튼 클릭 시 버튼 색상 변경(#210)

---

src/components/product/productlist/CategoryList.tsx
src/components/product/productlist/ProductItem.tsx
src/components/product/productlist/ProductSortButtons.tsx
src/containers/product/ProductSortContainer.tsx
src/pages/ProductListPage.tsx

네비게이션 카테고리 클릭 시 상품 아이템 width값이 다르게 보이던 이슈를 수정했습니다.
최상단 하위 컴포넌트에 width값을 px로 고정하는 코드를 추가하였습니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/28b3c98b-6b19-4e4a-baa3-84aa268c656c
#117

필터링 시 상품 크기 변화 이슈 수정(#117)

---

src/components/product/productlist/ProductItemList.tsx

상품 목록 페이지에서 필터링 후 해당하는 제품이 없을 경우 EmptyMessage 컴포넌트를 보여주는 코드를 추가했습니다.
https://github.com/Eurachacha/hanmogeum/assets/117130358/739fdc91-650f-4c7d-bc63-2c79eccb51cc
#277
EmptyMessage 컴포넌트 상단 margin에 대한 고민이 있습니다.

feat(ProductList): 상품 목록 페이지 조건부 렌더링 추가(#277)

---

src/components/product/productlist/ProductItem.tsx

상품을 클릭하면 product 객체 내 id 값을 바탕으로 상품 세부 페이지로 이동하는 코드를 추가했습니다.
https://github.com/Eurachacha/hanmogeum/assets/117130358/de294949-666c-486d-bdad-ed1ae207e28e
#280

feat(ProductList): 상품 클릭 시 상품 세부로 이동(#280)

---

src/apis/services/mypage.ts
src/assets/icons/dropDownArrow.svg
src/components/MypageDashBoard/WidgetShipping.tsx
src/components/common/Dropdown.tsx
src/components/mypage/ContainerHeader..tsx
src/containers/mypage/MyOrderDetailContainer.tsx
src/containers/mypage/MyOrderListContainer.tsx
src/types/myPage.ts
src/utils/getDateNow.ts

feat/mypage-orderlist-fix -> dev
- 마이페이지 기간별 조회페이지에서 필요하여, 드롭다운 컴포넌트를 추가하였습니다.
- 주문 목록 조회 시, 기간 별 조회 기능을 추가하였습니다.
- 주문 목록 요청 API를 하나로 통합하였습니다.
- 주문 목록 페이지의 사소한 디자인을 수정하였습니다.
ex) #111

fix(orderList): 주문 목록 페이지 기능 추가(#192)

---

src/Router.tsx
src/components/MypageDashBoard/WidgetMyInfo.tsx
src/components/mypage/NavigationMenu.tsx

feat/mypage-chore -> dev
- 대시보드 마이페이지 버튼 경로수정
- 네비게이션 메뉴에 필요한 페이지만 남김
- 마이페이지>에러페이지 컴포넌트는 하나로 관리하도록 수정
#284, #289, #285

bug(mypage): 마이페이지 사소한 코드 수정

---

src/Router.tsx
src/containers/mypage/MyOrderDetailContainer.tsx

ex) feat/login -> dev
- 사용자의 구매목록 주문 번호중 존재하지 않는 주문 번호를 URL로 직접 입력하여
들어갔을때
모달 창으로 안내 문구 표시 후 주문 내역 페이지로 이동하도록 수정하였습니다.
#291

bug(mypage): 존재하지 않는 주문번호의 URL로 들어갔을 때 버그 수정(#291)

---

src/apis/services/products.ts
src/components/product/productlist/ProductSortButtons.tsx
src/containers/product/ProductSortContainer.tsx
src/hooks/useQueryParams.tsx

상품 목록에서 정렬을 담당하는 필터링 기능을 구현합니다.
- 정렬 버튼 클릭 시 해당하는 쿼리스트링이 주소에 저장되도록 하는 함수를 생성했습니다. (useQueryParams의 toggleSortFilter)
- sortObject라는 이름의 객체를 생성하고, 쿼리스트링에 맞게 key: value를 저장합니다. 
- 쿼리스트링이 변경되면 실행하는 함수의 인자에 sortObject를 인자로 넘깁니다. 
- 받아온 sortObject를 JSON 문자열로 변환하여 api를 요청합니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/735824e1-0bb2-413a-9819-3d78c2b6235d
#268 
쿼리스트링을 index을 기준으로 저장할 경우 추후 요소가 삭제되었을 때 기대한 내용과 다르게 동작할 가능성이 있어 고정값으로 쿼리스트링을 저장하였습니다. 
```tsx
if (sortQuery === "0") {
sortObject.buyQuantity = 1;
} else if (sortQuery === "1") {
sortObject.createdAt = "1";
} else if (sortQuery === "2") {
sortObject.price = 1;
} else {
sortObject.price = -1;
}
```

feat(ProductList): 상품 목록 정렬 버튼 기능 구현(#268)

---

src/components/product/productlist/ProductItem.tsx

ProductItem 컴포넌트에서 에러를 발생시키는 hashTag map을 삭제했습니다.
https://github.com/Eurachacha/hanmogeum/assets/117130358/37dd8cc7-bac5-4a9c-a61f-e6bffe1dcff1
#298

fix(ProductLists): 모든 상품 이동 시 발생하는 에러(#298)

---

src/components/product/productlist/ProductItem.tsx

상품에 해당하는 라벨만 표시되도록 수정하였습니다.
https://github.com/Eurachacha/hanmogeum/assets/117130358/08707226-d415-4912-ac61-44bc8d5e4c08
#295

feat(ProductList): 상품에 해당하는 라벨만 붙이기(#295)

---

src/types/manage.ts
src/types/products.ts

shippingFees필드가 없으면 자동으로 배송비가 반영되므로 해당 필드를 제거했습니다.
상품등록 api에서 shippingFees 필드를 넣지 않으면 에러가 발생하는 문제가 있습니다.

chore(/types): product 타입에서 shippingFees 제거 (#308)

---

src/apis/instance.ts

`/admin`, `/seller` 요청 시 id필드를 담아 리턴하도록 응답인터셉터를 수정했습니다.

feat(admin): admin,seller요청 응답인터셉터 수정 (#313)

---

src/Router.tsx
src/components/login/Login.tsx
src/components/route/ProtectedRoute.tsx
src/containers/mypage/MyProfileLoginContainer.tsx
src/containers/mypage/MyProfileModifyContainer.tsx
src/containers/signUp/SignUpContainer.tsx
src/hooks/useAuthorization.ts
src/recoil/atoms/additionalAuthState.ts
src/types/routeAuthorization.ts

feat/route -> dev
- 마이페이지 > 내 정보 수정' 과 같이 추가 인증이 되어야 렌더링 되는 컴포넌트를 위해 상태관리 추가 후 관련 login 컴포넌트와 protectedRoute 옵션을 추가하였습니다.
-  내 정보 변경 시 추가인증 로그인 완료되어야 접근 가능하도록 수정하였습니다.
- 로그인한 사용자가 login, signup 페이지 접근 시 보이는 메시지와 location을 수정하였습니다.
`http://localhost:5173/mypage/profile/modify` URL 직접 입력 시 화면
#287

feat(auth): '마이페이지 > 내 정보 수정' 추가인증 확인 로직 추가

---

src/components/admin/ProductList.tsx
src/pages/ManagePage.tsx

- seller의 상품관리를 위한 탭과 상품목록을 출력했습니다.

feat(admin): 상품목록 불러오기(#330)

---

src/components/admin/OrderList.tsx
src/components/admin/ProductList.tsx
src/utils/getCodeValue.ts

- getCodeValue.ts 내부에서 훅을 사용해 발생하는 경고를 해결하기 위해 훅을 제거했습니다.
- 함수를 사용하는 곳에서 훅을 사용해 flattenData를 전달해야 합니다.

fix(admin): getCodeValue.ts 내부 훅 제거(#331)

---

src/components/product/productlist/ProductItemList.tsx
src/containers/product/ProductSortContainer.tsx

상품 목록 리스트에서 정렬되는 아이템 개수를 사용하는 쪽에서 props로 설정할 수 있도록 코드를 수정하였습니다.
**사용 예시1**
**사용예시2**
#321

fix(ProductList): 상품 아이템 개수 props로 수정(#321)

---

src/components/main/MainProductsList.tsx
src/containers/main/MainContainer.tsx

메인 페이지에 들어갈 ProductsList 컴포넌트를 생성했습니다.
캐러셀 기능은 배너 캐러셀이 완성된 뒤 추가할 예정입니다. 
#247 
**사용방법**
props로 products에는 type Product[] 형태의 데이터, title에는 메인 타이틀, content는 하단 타이틀 내용을 string 형태로 넣습니다. 
예시
```tsx
<MainProductsList products={newProducts} title="NEW ARRIVALS" content="한모금 상품을 가장 먼저 만나보세요!" />
```

feat(MainPage): 메인 페이지 product 컴포넌트 생성(#247)

---

src/pages/ProductDetailPage.tsx

- 상품상세페이지에서 장바구니에 담기 클릭 시 바로 헤더에 반영되지 않는 오류를 수정했습니다.

fix(상품상세): 장바구니에담기클릭시 헤더반영오류수정(#353)

---

src/components/admin/OrderEdit.tsx
src/pages/ManagePage.tsx

feat/login -> dev
- Order세부정보와 배송상태수정을 할 수 있는 OrderEdit컴포넌트를 구현했습니다.
스타일링 작업이 되지 않고 기능만 있는 상태입니다.

feat(admin): OrderEdit 컴포넌트 구현(#359)

---

src/apis/services/mypage.ts
src/apis/services/orders.ts
src/components/MypageDashBoard/WidgetShipping.tsx
src/components/mypage/OrderDetailInfo.tsx
src/constants/code.ts
src/containers/mypage/MyOrderDetailContainer.tsx
src/containers/mypage/MyOrderListContainer.tsx
src/types/myPage.ts
src/utils/getDateNow.ts

feat/mypage-orderdetail-cancle -> dev
- 주문 조회 기간의 마지막 일인 경우 조회에서 제거되어 조회 기간을 수정하였습니다.
- 백엔드api 개발이 완료되어, 주문 상세페이지 api를 추가하였습니다.
- 배송 코드에 따라 분기되는 로직에서 코드를 상수로 관리하도록 수정하였습니다.
- 주문 상세 페이지에서 주문 취소 버튼 로직을 추가하였습니다.
#349, #297, #293
관련 이슈에 있는 사항이 수정되었습니다.

feat(orderDetail): 주문 상세페이지 주문 취소 버튼 추가(#349, #297, #293)

---

src/apis/services/mypage.ts
src/components/MypageDashBoard/WidgetShipping.tsx

feat/mypage-order-widget-bug -> dev
- 마이페이지의 배송/조회 위젯에서 최대 3년까지의 배송만 확인 가능하도록 수정하였습니다.
#370

bug(widgetShipping): 배송조회 위젯에서 사용하는 api 요청 필터 수정(#370)

---

src/components/product/productlist/ProductItem.tsx

상품 아이템 컴포넌트 내 code로 되어 있던 teatype과 hashtag 데이터를 recoil에 저장돼있던 flattenCodeState를 사용해 변경하였습니다.
#209

fix(ProductList): 상품 내 code 데이터 value 변경(#209)

---

src/apis/services/admin/sellerDataProvider.ts
src/types/file.ts

- withLifecycleCallbacks를 사용해 beforeCreate 함수를 생성했습니다.
- beforeCreate에서 파일등록 요청 후 create함수에서 상품등록 요청을 보냅니다.

파일등록 기능 구현 및 상품등록 API 연결(#393)

---

src/components/cart/CartItem.tsx

- image타입 변화로 사진이 깨졌던 오류를 해결했습니다.

fix(cart): 장바구니 사진깨짐오류 해결(#372)

---

src/components/cart/CartItem.tsx

- 재고가 부족하여 수량이 자동으로 반영되는 경우 체크박스 배열에서 삭제하여 구매하기버튼을 바로 눌러도 함께 넘어가지 않도록 했습니다.

fix(cart): 재고부족 수량자동반영시 체크해제(#405)

---

src/components/cart/CartItem.tsx

- 카운터 상단에 재고: n개 문구 출력
- 수량 자동반영 시 안내문구 출력

feat(cart): 장바구니 페이지 재고 안내 및 재고반영안내메시지 출력(#403)

---

src/pages/OrderCheckoutPage.tsx
src/types/orders.ts

- 구매 요청 시 location.state가 없으면(detailpage에서 넘어온 경우) `type: "cart"`필드와 함께 요청하도록 했습니다.

fix(cart): cart상품 주문후 상품이 남아있는 오류 해결(#373)

---

src/components/common/Header.tsx
src/pages/OrderCheckoutPage.tsx

- `type: "cart"`필드가 있는 주문 후에 cartStorage에 cart정보를 받아와 새롭게 저장합니다.
- 헤더에서 cartStorage변화를 감지해 카운트넘버가 수정됩니다.

fix(cart): 주문후 장바구니상품수 헤더반영 오류 해결(#410)

---

src/components/MypageDashBoard/WidgetMyInfo.tsx
src/components/MypageDashBoard/WidgetTodayTea.tsx
src/components/common/Footer.tsx
src/components/common/Header.tsx
src/components/mypage/OrderDetailInfo.tsx
src/containers/mypage/MyOrderDetailContainer.tsx
src/containers/mypage/MyOrderListContainer.tsx

feat/chore-bugs -> dev
- 마이페이지 > 오늘의 추천차 버튼 클릭 시 상세페이지로 이동
마이페이지 > 상단 대시보드의 오늘의 추천차 버튼 클릭 시 상세페이지로 이동하도록 추가하였습니다.
-  footer margin 추가
- 주문 상세페이지 > 화면 깨지는 현상을 위해 min-width 설정
- 주문 상세페이지 > 리뷰하기 버튼 삭제
- 주문 상세페이지 > 주문 취소 후 상품 이미지 색 조정
- 주문 상세페이지 > 주문번호 대신 user의 id가 표시되는 버그를 수정
- 주문 내역페이지 > 주문내역에 주문 상품이 여러개인 경우 `...외 N개`와 같은 표시가 안되는 버그 수정
- 헤더에 검색 마크업 제거
#416 #412 #411 #399 #390 #377 #376 #375 #364

bug(Mypage, Header, Footer): 간단한 버그/마크업 수정

---

src/pages/OrderCheckoutPage.tsx

feat/cart-> dev
- 바로구매 버튼으로 상품 구매시 장바구니 상품이 전부 구매되는 버그를 해결했습니다.
- location.state 존재 여부에 따라 주문하는 데이터를 다르게 처리했습니다.

fix(cart): 바로구매시 장바구니상품 반영 버그 해결(#418)

---

src/components/product/productlist/ProductItem.tsx

productItem code 값으로 value 불러오는 코드에서 발생하는 에러를 수정하였습니다.
배열을 toString으로 변경하여 key 값으로 활용하였으나 배열 길이가 한 개 이상인 경우가 있어 에러가 발생했습니다.
해당 코드를 첫 번째 요소만 가져오는 코드로 수정하였습니다. 
#421

fix(ProductList): 상품 value 불러오는 에러 수정(#421)

---

src/containers/cart/CartItemContainer.tsx
src/containers/cart/CartItemListContainer.tsx

- 선택상품삭제, 단일상품삭제 후 체크박스 상태를 업데이트하는 코드를 추가했습니다.

fix(cart): 비로그인 상품삭제시 체크박스버그해결(#433)

---

src/components/common/Header.tsx

- 재고가 0개인 상품은 헤더의 개수에 반영하지 않도록 필터링했습니다.
- 카트에 머무르다가 새로고침 후 재고가 0개가 된 아이템은 개수반영에 제외합니다.

fix(cart): 수량자동반영시 헤더개수반영버그 해결(#413)

---

src/components/product/productlist/ProductItem.tsx

상품 아이템 하단 이미지가 가려지는 이슈를 해결했습니다. 
또한 `background 속성`으로 지정돼있던 이미지를 `img 태그`로 수정하였습니다. 
#429

fix(ProductList): 상품 아이템 하단 가려짐 이슈 해결(#429)

---

src/components/product/productlist/ProductItem.tsx

상품 아이템 가격 표시 영역에 원화 표시로 변환하는 유틸 함수 `getPriceFormat`을 사용했습니다.
#301

fix(ProductList): 상품 아이템에 단위 코드 추가(#301)

---

src/Router.tsx
src/components/common/Header.tsx
src/pages/AdminPage.tsx

- AdminPage 라우팅 설정
- userType 별 헤더 링크 url 반영
- 새탭에서 열리도록 설정

feat(admin): 헤더 관리자페이지 링크 라우팅 수정(#398)

---

src/pages/ProductDetailPage.tsx

- 상품 메인 이미지와 상품상세정보 content를 출력합니다.
content 이미지 출력이 안되거나 누락된 아이템이 있습니다.

feat(상품상세): 메인이미지및 상세정보 출력(#441)

---

src/containers/mypage/MyProfileModifyContainer.tsx
src/containers/orderCheckout/ShippingInfoContainer.tsx
src/containers/signUp/SignUpContainer.tsx

feat/order-checkout-shipping-> dev
- 구매하기 페이지에서 배송 주소는 주소 api로 추가할 수 있도록 하였습니다.
- 전화번호 입력 input  관련 코드에서 ITU 권고 원칙인 (전화번호 최대 길이: 15) + (하이픈 :2개)를 더한 17글자로 수정하였습니다.
#382

bug(orderCheckout): 구매하기페이지 배송정보 검증 추가(#382)

---

src/pages/ErrorPage.tsx

애러페이지를 구현했습니다. 잘못된 경로에 들어올 경우 띄워지는 화면으로 `홈으로 돌아가기` 버튼을 넣었습니다. 
#286 
상하 중앙 정렬 이슈

feat(ErrorPage): 에러페이지 디자인 및 구현(#286)

---

src/components/common/Modal.tsx

feat/modal-z-index -> dev
- 헤더 z-index가 백드롭 뒤에 오도록 모달 백드롭 값을 수정하였습니다.
#497

design(Modal): 모달 백드롭 z-index 수정(#497)

---

src/containers/product/ProductSortContainer.tsx

상품목록페이지 api 요청 함수를 react-query를 사용해 변경하였습니다.
staleTime을 10분으로 설정하여 동일한 필터링에 대한 데이터 요청을 줄여 성능을 개선하였습니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/c553450b-ca27-47ae-8235-b240b4e06eab
#515 
사용하지 않는 error 제거

refactor(ProductList): 상품목록페이지 react-query 도입(#515)

---

src/components/product/productlist/ProductSortButtons.tsx

선택한 정렬 버튼에 CSS를 추가해 선택하지 않은 버튼과 차이를 뒀습니다.
필터링 버튼과 마찬가지로 쿼리스트링에 value값 존재여부를 확인해 코드를 작성했습니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/0ba13bcc-6ba3-44af-80e9-4887752ed6c6
#517

fix(ProductList): 선택한 정렬버튼 CSS 추가(#517)

---

src/App.tsx
src/apis/instance.ts
src/components/common/LoadingSpinner.tsx
src/components/common/TokenExpireModal.tsx
src/hooks/useAxiosInterceptor.ts
src/pages/AdminPage.tsx
src/pages/SellerPage.tsx
src/recoil/atoms/tokenExpireModalState.ts

feat/token-refresh -> dev
- refresh토큰 만료 여부를 recoil에 저장
- refresh토큰 만료 안내 모달 생성
- axios 인터셉터를 훅으로 분리
- 각 레이아웃 페이지에서 모달 연결
- 로딩스피너 z-index 삭제
모달출력시 로딩스피너가 z-index설정으로 모달 출력에 문제가 있어 수정했습니다. @jungmyungjin

feat(token): 토큰 리프레시 요청 실패시 로그아웃 처리(#462)

---

src/pages/ProductDetailPage.tsx

- width가 달라짐에 따른 반응형을 구현했습니다.
- 우측 컨트롤박스(유저 상호작용)부분은 스크롤을 내려도 고정되어있도록 했습니다.

feat(상품상세): 반응형 구현 및 유저 상호작용부 fixed처리(#542)

---

src/components/admin/SideMenu.tsx
src/pages/SellerPage.tsx

design(seller): 타이틀 및 좌측메뉴 스타일링(#553)

---

src/containers/orderCheckout/ShippingInfoContainer.tsx
src/pages/OrderCheckoutPage.tsx

phone 인풋에 입력 시 autoHyphen이 적용되어 state에 저장됨.
하이픈이 포함된 전화번호 문자열을 validate하기 때문에 계속해서 오류가 남.
-> phone state에서 하이픈 제거 후 validation을 돌리도록 수정했습니다.

fix(구매하기): 배송정보 validation버그 해결(#555)

---

src/components/recommend/TeaSurvey.tsx
src/pages/TeaSurveyResultPage.tsx

메인에서 배너를 클릭하면 나오는 차 추천페이지를 작업하였습니다.
- 클릭 시 버튼 활성화
- 결과보기 버튼 클릭 시 해당하는 제품 필터링되어 출력
- 배포 주소 바탕으로 링크 복사
- 다시 결과보기 클릭 시 설문 페이지로 이동
https://github.com/Eurachacha/hanmogeum/assets/117130358/c458ec96-8fbd-4471-848e-4760198b4253
#315 
모든 버튼을 클릭해야 설문 결과가 나오도록 하는 코드 추가

feat(TeaSurvey): 추천페이지 작업(#360)

---

src/apis/services/products.ts
src/components/product/productlist/ProductItemList.tsx
src/containers/product/ProductSortContainer.tsx
src/types/products.ts

상품 목록 페이지에 페이지네이션을 적용하여 6개씩 보여주는 코드를 추가했습니다.
#344 
무한스크롤을 적용하려다 페이지네이션으로 변경하였습니다.

feat(ProductList): 상품 목록 페이지네이션 적용(#344)
