Eurachacha/hanmogeum

- src/components/common/Footer.tsx
Footer 컴포넌트 구현
feat/footer -> dev
- Footer 구현
> feat(@/components/common): Footer 구현 (#20)

- src/components/common/Footer.tsx
ex) feat/footer-mapping-bug -> dev
- 콘솔 에러가 나지 않도록 map으로 반복하여 출력하는 대상에
각각 다르게 key를 설정하였습니다.
> bug(@/components/common): map item에 key추가, 주석제거

- src/components/common/Button.tsx
feat/common-button-component -> dev
실수로 잘못 입력한 스타일링코드 한줄 삭제
ex) #22
> fix(Button.tsx): 잘못 입력한 스타일링코드 삭제 (#22)

- src/components/ContentsTitle/ContentsTitle.tsx
- src/components/SectionTitle/SectionTitle.tsx
ex) feat/contents-title -> dev
- 기본 스타일을 적용하되, 추가 커스텀이 가능한 ContentsTitle 컴포넌트를 구현하였습니다.
> feat(@/components/SectionTitle): ContentsTitle 컴포넌트개발(#52)

- src/types/products.ts
ex) feat/category-button-list-component -> dev
interface products와 extra에 변경된 타입을 반영하여 수정했습니다.
interface Product에 buyQuantity와 quantity를 추가하였고, 
Extra에 isDecaf, pack, hashtag, taste, teaType을 추가하고 category, quantity, buyQuantity, order를 제거하였습니다. 
ex) #60
> fix(types): products interface에 변경된 타입  반영(#60)

- src/styles/reset.css
feat/box-sizing -> dev
- 모든 태그에 box-sizing을 적용
> feat(reset.css): 모든 태그 box-sizing 추가 (#66)

- src/components/cart/CartItem.tsx
- src/pages/CartPage.tsx
@/containers/cart import문을 수정했습니다.
> chore(cart): @/containers/cart import문 수정 (#70)

- src/components/common/Header.tsx
feat/header-auth -> dev
- 테스트 용으로 사용된 잘못된 스타일을 제거하였습니다.
ex) #111
> design(header): 테스트 용 css 제거

- src/components/common/Footer.tsx
- src/components/common/Header.tsx
feat/footer-style-fix -> dev
- header, footer의 최소 크기 이하인 경우 화면이 깨지는 현상으로 인해 overflow시 hidden 설정 하였습니다.
- 그 외 간단한 footer의 디자인 수정도 하였습니다.
#77
> design(header,footer): overflow: hidden 설정 (#77)

- src/components/common/Input.tsx
feat/Input-style-fix -> dev
- Input 글씨크기, padding 수정하였습니다.
- 기존 customStyle을 특정 속성만 사용할 수 있도록 범위 수정하였습니다.
#79, #54
> design(footer): 디자인 수정, 커스텀 스타일 범위 수정 (#79)

- src/Router.tsx
- src/components/common/Header.tsx
- src/pages/ManagePage.tsx
feat/signup -> dev
- 카테고리 경로 수정에 따른 로직 변경
- 관리자 페이지 생성 
#97
반영 브랜치명을 잘못 사용하여 반영을 하였으나,
큰 문제가 없어서 merge 합니다.
> feat(Header): 카테고리 경로 수정에 따른 로직 변경 (#97)

- src/components/common/Price.tsx
- src/components/orderCheckout/FormInput.tsx
- src/components/orderCheckout/OrderItem.tsx
- src/constants/order.ts
- src/containers/cart/CartPriceContainer.tsx
- src/containers/orderCheckout/OrderInfo.tsx
- src/containers/orderCheckout/OrderListContainer.tsx
- src/containers/orderCheckout/OrderPriceContainer.tsx
- src/containers/orderCheckout/ShippingInfoContainer.tsx
- src/containers/orderCheckout/UserInfoContainer.tsx
- src/pages/CartPage.tsx
- src/pages/OrderCheckoutPage.tsx
> feat(orderCheckout): 주문하기 페이지 기본 마크업 (#84)

- src/containers/SignUpContainer/SignUpContainer.tsx
- src/types/users.ts
feat/signup-bug -> dev
- 회원가입 시 전화번호 response data에 하이픈이 하나만 빠지는 버그를 수정하였습니다.
- 등록된 이메일인 경우 올바른 에러 메시지를 출력하지 않는 버그를 수정하였습니다.
- input 에 값이 없는경우 오류 메시지가 출력되지 않도록 수정하였습니다.
- 사용하지 않는 type을 제거하였습니다.
> bug(SignUp): 중복체크, 휴대폰번호 버그 수정 (#95)

- src/components/ContentsTitle/ContentsTitle.tsx
- src/containers/SignUpContainer/SignUpContainer.tsx
- src/types/customStyle.ts
- src/types/input.ts
feat/customSTyle -> dev
- customStyle의 타입을 interface로 관리하도록 하였습니다.
> fix(customStyle): 컴포넌트의 customStyle 범위 지정 (#54)

- src/constants/localstorageKeys.ts
- src/containers/LoginContainer/LoginContainer.tsx
- src/containers/SignUpContainer/SignUpContainer.tsx
- src/pages/LoginPage.tsx
- src/pages/SignUpPage.tsx
- src/recoil/atoms/loggedInUserState.ts
feat/convention -> dev
-  로그인 페이지의 회원가입 오타 수정
- ocalstorageKeys 파일 export 방식 수정
- 카멜케이스가 아닌 폴더명 수정
> 컨벤션 안맞는 코드 수정 자잘한 버그 수정

- src/components/product/productlist/CategoryButtonList.tsx
ex) feat/product-list-> dev
- 버튼 클릭 시 해당하는 쿼리스트링 주소에 한글로 저장되어 있던 요소를 코드값으로 변경했습니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/4165044e-05c5-425c-9558-7dac794da12c
#124
> fix(ProductList): 쿼리스트링 코드값으로 변경(#124)

- src/types/users.ts
feat/add-type-chore-> dev
- 작업 중 삭제된 interface를 추가했습니다.
#145
> bug(user.ts) 삭제된 interface 타입 원복 (#145)

- .eslintrc
- src/apis/services/orders.ts
- src/components/cart/CartItem.tsx
- src/components/common/Header.tsx
- src/containers/LoginContainer/LoginContainer.tsx
- src/containers/SignUpContainer/SignUpContainer.tsx
- src/containers/cart/CartItemContainer.tsx
- src/containers/cart/CartItemListContainer.tsx
- src/containers/cart/CartPriceContainer.tsx
- src/pages/CartPage.tsx
- src/recoil/atoms/cartState.ts
- src/types/cart.ts
- src/types/orders.ts
- src/types/users.ts
- 장바구니 recoil state 타입 수정
- 체크된 장바구니 아이템 상태 배열에 장바구니 아이템 id 대신 해당 상품의 id를 담도록 수정
- 로그인 여부에 따른 장바구니 기본 기능 구현
- 로그인한 유저의 extra필드가 없을 때 장바구니 정보를 불러오지 못하는 에러 해결
- 구매하기 페이지로 이동하기 구현
#150 #151 #152 #133 #119 #154 #155 #156
> feat(cart): 장바구니페이지 기본기능 구현 및 에러 해결

- src/components/common/Modal.tsx
feat/Modal -> dev
모달 사용시 버튼 정렬이 깨지는 문제 해결을 위해 center 처리 했습니다.
> chore(Modal): ButtonArea justify-content:center 처리 (#158)

- src/containers/cart/CartPriceContainer.tsx
비로그인 유저가 구매하기 버튼 클릭 시 로그인페이지로 리다이렉트 처리 했습니다.
> feat(cart): 비로그인 구매하기 클릭시 /login으로 이동 (#135)

- src/containers/orderCheckout/OrderInfo.tsx
- src/containers/orderCheckout/OrderListContainer.tsx
- src/containers/orderCheckout/OrderPriceContainer.tsx
- src/pages/OrderCheckoutPage.tsx
- 구매하기 페이지 초기 접속 시 재고를 체크합니다.
- 재고 부족시 모달을 띄웁니다.
- 모달 확인 클릭 시 이전 페이지로 이동합니다.
> feat(orderCheckout): 초기 접속시 재고 체크 후 모달 생성 (#161)

- src/containers/orderCheckout/ShippingInfoContainer.tsx
> feat(orderCheckout): 주소찾기 기능 연결 (#83)

- src/types/orders.ts
주문 요청 시 request body 타입을 수정했습니다.
> feat(orders.ts): POST /orders 요청 data 타입 수정 (#165)

- src/containers/orderCheckout/OrderInfo.tsx
- src/containers/orderCheckout/ShippingInfoContainer.tsx
- src/pages/OrderCheckoutPage.tsx
- src/types/orders.ts
배송정보를 입력받아 주문 요청을 구현했습니다.
배송정보가 입력되지 않은 경우 모달로 안내를 하도록 했습니다.
> feat(주문하기): 상품및배송 정보로 주문 요청 구현 (#83)

- package-lock.json
- package.json
- src/components/common/Firecracker.tsx
- src/containers/SignUpContainer/SignUpContainer.tsx
- src/pages/MainPage.tsx
feat/signUp-congratulation -> dev
- react-confetti-explosion 라이브러리를 사용하여 폭죽을 터트리는 효과 구현하였습니다.
#172)
> feat(Firecraker): 회원가입 완료 후 폭죽 이펙트 추가 (#172)

- package-lock.json
- src/containers/orderCheckout/ShippingInfoContainer.tsx
- src/containers/orderCheckout/UserInfoContainer.tsx
- 전화번호 출력, input에서 autoHyphen을 적용했습니다.
> feat(orderCheckout): 전화번호 autoHyphen 적용 (#174)

- src/containers/LoginContainer/LoginContainer.tsx
- src/recoil/selectors/codeSelector.ts
- src/recoil/selectors/loggedInUserSelector.ts
- src/utils/getDate.ts
feat/fix-typo -> dev
- 함수, 변수 오타 수정
> chore(util,selector): 함수, 변수 오타 수정

- src/components/contentsTitle/ContentsTitle.tsx
- src/components/itemInput/ItemInput.tsx
- src/containers/loginContainer/LoginContainer.tsx
- src/containers/signUpContainer/SignUpContainer.tsx
feat/folder-name -> dev
- 이전 폴더명 변경 후, 팀원들 폴더명은 변경되지 않은 이슈 해결을 위해
`git config core.ignorecase false` 명령을 통해 수정하였습니다.
ex) #111
> rename(components, containers): 폴더명 카멜케이스로 수정 (#123)

- src/apis/services/cart.ts
- src/components/cart/CartItem.tsx
- src/containers/cart/CartItemContainer.tsx
- src/containers/cart/CartItemListContainer.tsx
- src/types/cart.ts
- src/types/orders.ts
- recoil 장바구니 state에 stock(재고) 필드 추가
- 장바구니 재고 조회 요청 함수 생성
- 비로그인 유저 장바구니 초기접속시 재고 조회요청 API 연결
#189 #195 #196
> feat(cart): 비로그인 유저 장바구니 초기접속시 재고 조회요청 API 연결 (#154)

- src/containers/SignUpContainer/SignUpContainer.tsx
- src/containers/mypageContainer/MyProfileModifyContainer.tsx
- src/containers/signUpContainer/SignUpContainer.tsx
feat/mypge-profile-modify-bug -> dev
- 회원가입 시 상세주소 필드를 생성하도록 api 요청 데이터에 추가하였습니다.
- 사용자 정보 수정 시, 비밀번호 확인 입력값이 없더라도 수정되는 버그를 수정하였습니다.
ex) #111
> bug(signUp,MyProfileModify): 상세 주소 필드 추가 (#193)

- src/components/product/productlist/CategoryButton.tsx
- src/hooks/useQuantityCounter.ts
- src/pages/ProductDetailPage.tsx
- 상품상세페이지 마크업
- 수량조절 커스텀훅 생성
- CategoryButton 컴포넌트 스타일 수정 및 onClick 옵셔널 처리
#113 #203 #205
> feat(productDetail): 상품상세페이지 마크업 및 수량조절 커스텀훅 생성

- src/containers/cart/CartItemListContainer.tsx
- 비로그인상태로 장바구니 접속한 경우의 무한렌더링 문제를 해결했습니다.
> fix(cart): 비로그인상태로 접속시 무한렌더링문제 해결 (#206)

- src/containers/cart/CartItemListContainer.tsx
- 로그인 상태로 장바구니 접속 시 모든 체크박스가 체크되지 않는 문제를 해결했습니다.
> feat(cart): 로그인접속시 모두체크되지 않는 문제 해결(#214)

- src/components/login/Login.tsx
feat/login-cart -> dev
- 로그인 성공 시 장바구니에 담겨있던 상품과 기존에 담았던 상품을 합치고, 상태를 업데이트 하는 로직을 추가하였습니다.
ex) #111
> feat(login): 로그인 성공 시 장바구니 합치기 로직 추가(#213)

- src/components/common/Header.tsx
feat/header-cart -> dev
- 비회원 상태에서도 장바구니에 상품 추가 시 헤더에 갯수가 표시되도록 수정하였습니다.
ex) #111
> bug(header): 비회원 장바구니 갯수 표시 버그 수정(#212)

- src/components/cart/CartItem.tsx
- src/hooks/useQuantityCounter.ts
- useQuantityInput에 재고 부족시 재고수량을 input에 세팅하는 함수를 생성했습니다.
- 수량조절 로직 커스텀 훅을 장바구니에서 연결하여 사용하도록 수정했습니다.
> refactor(cart): 수량조절커스텀훅 장바구니에 연결 (#205)

- src/containers/cart/CartItemContainer.tsx
- src/containers/cart/CartItemListContainer.tsx
- src/pages/CartPage.tsx
체크박스모두체크 세팅을 CartPage에서 하도록 수정했습니다.
> refactor(cart): 체크박스세팅을 CartPage에서 하도록 수정(#239)

- src/components/login/Login.tsx
- src/containers/login/LoginContainer.tsx
feat/login-redirect -> dev
- 로그인페이지에서 로그인 완료 후 이전 페이지로 리다이렉트 하도록 하였습니다.
- 사용자 정보 수정 컴포넌트에서도 이상이 없음을 확인하였습니다.
ex) #111
> fix(login): 로그인 완료 후 이전 페이지로 리다이렉트 (#218)

- src/apis/services/products.ts
products 검색 요청 시 변경된 데이터를 반영하였습니다.
#244
> fix(api): products api 변경된 주소 반영(#244)

- src/hooks/useQuantityCounter.ts
재고 부족 시 재고가 반영된 경우 updated state가 true로 설정되고,
이후 input 조작 시 false로 초기화되도록 구현했습니다.
#207
> feat(useQuantityCounter): 재고반영여부 state 생성(#249)

- src/hooks/useQueryParams.tsx
디카페인 토글 클릭 시 쿼리스트링에 false 값까지 담기던 오류를 수정했습니다.
https://github.com/Eurachacha/hanmogeum/assets/117130358/c807431c-35e9-42ec-9f8d-2d49cdca663e
#243
> fix(hooks): 디카페인 토글 클릭 시 쿼리스트링 수정(#243)

- src/apis/services/products.ts
- src/components/product/productlist/CategoryList.tsx
- src/containers/cart/CartItemContainer.tsx
- src/pages/MainPage.tsx
상품 목록 api를 요청하는 함수를 수정했습니다.
착각하여 MainPage와 CategoryList 변경 사항을 같이 반영한 부분이 있습니다. 추후 수정하겠습니다..
#87
> feat(apis): 상품 목록 데이터 요청하는 함수 수정(#87)

- src/components/mypage/ContainerHeader..tsx
- src/components/mypage/OrderDetailInfo.tsx
- src/containers/mypage/MyOrderDetailContainer.tsx
- src/containers/mypage/MyOrderListContainer.tsx
feat/mypage-orderdetail -> dev
- 상품 상세 각 상품 아이템 컴포넌트를 수정하였습니다.
- 상품 상세페이지의 주문 정보 컴포넌트 화면을 수정하였습니다.
ex) #111
> fix(MyOrderDetail): 상품 상세 상품 페이지 수정(#184)

- src/pages/MainPage.tsx
메인 페이지에서 작업했던 불필요한 코드를 삭제하였습니다.
#303
> fix(MainPage): 메인페이지 불필요한 코드 제거(#303)

- package-lock.json
- package.json
- src/types/orders.ts
- react-admin 라이브러리 설치( #296 )
- orderDetail 타입 수정( #306 )
DB의 orderDetail 타입이 맞지 않는 데이터들을 삭제했습니다.
> feat(admin): react-admin 설치 및 orderDetail 타입 수정(#306)

- src/Router.tsx
- 관리자페이지가 App하위에서 라우팅되지 않도록 수정했습니다.
> feat(admin): 관리자페이지 라우팅 수정 (#310)

- src/apis/services/admin/dataProvider.ts
- dataProvider 함수 중 getList 함수를 타입에 맞게 세팅했습니다.
> feat(admin): dataProvider getList 함수 세팅(#312)

- src/components/admin/OrderList.tsx
- src/pages/ManagePage.tsx
- AdminComponent 하위에 Resource 컴포넌트를 불러오고 OrderList 컴포넌트를 연결했습니다.
> feat(admin): 주문내역 불러오기(#316)

- src/types/products.ts
- mainImages 저장 형태가 수정됨에 따라 타입을 수정했습니다.
> feat(types): product mainImages 타입 수정(#319)

- src/Router.tsx
- src/components/route/ProtectedRoute.tsx
- src/hooks/useAuthorization.ts
- src/types/routeAuthorization.ts
- src/types/users.ts
feat/route -> dev
- Router.tsx에서 사용될 하위 하위 라우터 접근 시 권한을 확인하는 컴포넌트를 구현하였습니다.
- 사용자 권한이 목록에 있는 권한에 충족하는지 체크하는 커스텀 훅을 구현하였습니다.
#287
> feat(route,hook): 라우터 접근권한 확인 컴포넌트, 커스텀 훅 구현(#287)

- src/types/manage.ts
- manage.ts에서 mainImages의 변경된 형태를 반영해 수정했습니다.
> feat(types): manage.ts mainImages 타입 수정 (#319)

- src/components/route/ProtectedRoute.tsx
feat/login-bug -> dev
- 에러 메시지 확인 후 버튼 클릭 시 기본 이벤트가 발생하지 않도록 하였습니다.
#327
> bug(ProtectedRoute): 기본 이벤트 제거(#327)

- src/pages/ManagePage.tsx
- ManagePage에서 코드 정보를 요청하고 recoil에 저장하도록 했습니다.
> feat(admin): ManagePage에서 code정보 recoil에 저장(#331)

- src/components/admin/OrderList.tsx
- src/components/admin/ProductList.tsx
- src/utils/getCodeValue.ts
- 코드값으로 해당하는 value를 불러오는 util함수를 생성했습니다.
- ProductList와 OrderList에서 활용하도록 수정했습니다.
> feat(admin): 코드value를 반환하는 함수 생성및적용(#334)

- src/apis/services/products.ts
productsApi 내 isNew가 true인 상품을 가져오는 getProductByIsBest 함수명을 getProductByIsNew로 변경하고
isBest가 true인 상품을 가져오는 getProductByIsBest 함수를 생성하였습니다.
#322
> fix(apis): productsApi 내 함수명 변경(#322)

- src/containers/cart/CartItemListContainer.tsx
- 비로그인 상태에서 장바구니 접속 시 상품이 모두 사라지는 문제 해결
> fix(cart): 비로그인시 장바구니 오류 해결(#340)

- src/components/product/productlist/ProductItem.tsx
feat/main-products -> dev
상품 이미지를 불러오는 코드를 데이터에서 제공되는 형태로 변경하였습니다.
#320
> fix(ProductList): product 이미지 불러오는 형식 수정(#320)

- src/containers/main/MainContainer.tsx
MainProductsList를 불러오는 이름을 BestProducts에서 MainProductsList로 변경하였습니다.
#247
> fix(MainPage): MainProductsList import 이름 수정(#247)

- src/components/route/ProtectedRoute.tsx
- src/hooks/useAuthorization.ts
feat/route-refresh-bug -> dev
- 상품페이지에서 새로고침 시 메인페이지로 가는 버그를 수정하였습니다.
- ProtectedRoute에서 버그유발하는 불필요 로직을 수정하였습니다.
- useAuthorization 훅에서 사용자 상태가 변경되는 경우 인증 상태에 반영되도록 수정하였습니다.
#350 이슈도 함께 처리되었습니다.
> bug(route): 상품 페이지에서 새로고침 시 메인페이지로 가는 버그(#348)

- src/containers/orderCheckout/OrderInfoContainer.tsx
- src/pages/OrderCheckoutPage.tsx
feat/loggedin-order-bug -> dev
- 영채님과 페어코딩으로 해결하였습니다.
#347
> bug(orderCheckout): 로그인된 사용자 장바구니 구매 버그 수정(#347)

- src/apis/services/admin/sellerDataProvider.ts
- src/pages/ManagePage.tsx
- sellerDataProvider를 분리하고, getOne과 update함수를 수정했습니다.
#336
> feat(admin): seller프로바이더분리및getOne,update작성(#355)

- src/apis/instance.ts
- 응답 데이터가 ok, item 으로 구성되지 않는 요청에 대한 처리를 했습니다.
> feat(admin): 관리자api요청시의 응답인터셉터 수정(#357)

- src/Router.tsx
- src/pages/SellerPage.tsx
- ManagePage를 SellerPage로 변경하고 Router.tsx에도 반영했습니다.
> feat(admin): Router.tsx SellerPage 연결(#362)

- src/containers/orderCheckout/OrderListContainer.tsx
- src/types/cart.ts
- src/types/orders.ts
feat/imageUrl -> dev
- cart와 구매하기 관련 상품이미지 타입 변경 내용을 적용했습니다.
> feat(cart, order): 상품이미지 타입 변경내용 적용(#320)

- src/components/product/productlist/CategoryButton.tsx
- src/components/product/productlist/CategoryButtonList.tsx
- src/pages/ProductDetailPage.tsx
feat/CategoryButton -> dev
- children을 따로 받지 않고 code만 받아 리턴하도록 수정했습니다.
- onClick이벤트에 들어갈 함수와 disabled속성을 옵셔널 props로 받습니다.
> feat(CategoryButton): props수정 및 사용코드 수정(#281)

- src/containers/orderCheckout/ShippingInfoContainer.tsx
feat/ShippingInfo -> dev
- order요청시 상세주소가 주소와 별개의 필드에서 관리되도록 수정했습니다.
> feat(ShippingInfo): order테이블 detailaddress반영(#193)

- src/components/MypageDashBoard/WidgetTodayTea.tsx
- src/containers/mypage/MyOrderDetailContainer.tsx
- src/containers/mypage/MyOrderListContainer.tsx
- src/types/myPage.ts
feat/mypage-imgae-> dev
- 상품 경로를 backend 주소의 이미지 경로로 구하도록 수정하였습니다.
- 백엔드 서버의 상품 이미지의 상세 경로 수정에 따라 마이페이지 이미지 주소도 수정하였습니다.
#320
> fix(product): 상품 이미지 경로 수정에 따른 로직 수정 (#320)

- package-lock.json
- package.json
- src/apis/services/mypage.ts
- src/containers/mypage/MyOrderListContainer.tsx
- src/types/myPage.ts
feat/mypage-order-pagenation -> dev
- mui 디자인 프레임워크를 설치 후, 주문 내역 페이지네이션을 추가하였습니다.
#183
> feat(MyOrderList): mui 프레임워크를 사용하여 주문 내역 페이지네이션 추가(#183)

- src/containers/product/ProductSortContainer.tsx
상품 목록 페이지에서 '인기순'과 '최신순' 정렬 이슈를 수정했습니다.
https://github.com/Eurachacha/hanmogeum/assets/117130358/8d1b697b-d71e-4194-b63b-7c4ca116937e
#381
> fix(ProductList): 상품 목록 페이지 정렬 에러 수정(#381)

- src/apis/instance.ts
- 파일 업로드 시 사용할 instance를 생성했습니다.
> feat(admin): 파일 업로드 인스턴스 생성(#385)

- src/components/admin/ProductCreate.tsx
- src/pages/SellerPage.tsx
- 상품목록페이지에서 상품등록 페이지로 접근할 수 있습니다.
- 상품등록 폼을 생성했습니다.
> feat(admin): 상품등록 페이지 기본 폼 생성(#389)

- src/components/common/Modal.tsx
- src/pages/OrderCheckoutPage.tsx
- 결제하기 버튼 클릭시 재고 부족으로 에러가 발생하면 모달을 띄우고 이전 페이지로 이동합니다.
> feat(구매하기): order요청 에러처리(#171)

- package-lock.json
- package.json
- src/components/common/Carousel.tsx
- src/components/main/MainBanner.tsx
메인 페이지 배너를 react-slick을 사용하여 추가하였습니다.
#142 
캐러셀 코드만 커밋하여 아직 화면에 변화되는 부분은 없습니다.
> feat(MainPage): 메인페이지 배너 캐러셀 추가(#142)

- src/containers/mypage/MyProfileModifyContainer.tsx
- src/types/users.ts
feat/mypage-profile-modify-bug -> dev
- 내 정보 변경 페이지에서 기본 정보 불러오도록 수정하였습니다.
- 내 정보 변경 버튼 클릭시 페이지가 안넘어가는 버그를 수정하였습니다.
ex) #111
> bug(mypage): 마이페이지 > 내 정보 변경 페이지의 버그 수정

- src/containers/cart/CartPriceContainer.tsx
- 체크되어있으면서 수량이 0이 아닌 상품만 계산하도록 수정했습니다.
> fix(cart): 수량 자동반영 후 가격안내반영 버그 해결(#415)

- src/apis/instance.ts
- src/apis/services/admin/sellerDataProvider.ts
- privateInstance 응답인터셉터에서 item 필드에 data.ok 담아서 리턴
- sellerDataProvider delete, deleteMany 함수 요청 uri 수정
> feat(seller): 상품삭제기능 구현

- src/apis/services/mypage.ts
- src/components/MypageDashBoard/WidgetShipping.tsx
feat/mypage-shipping-api -> dev
- 마이페이지 > 주문/배송 위젯 api를 새로 만들어진 api로 수정하였습니다.
> fix(MypageDashBoard): 주문/배송 위젯 api 수정(#423)

- src/components/product/productlist/ProductItem.tsx
- src/components/product/productlist/ProductItemList.tsx
- 상품 목록 페이지 미디어쿼리를 추가하였습니다.
- 상품 목록 페이지 해시 태그 ui를 수정하였습니다.
- 상품 이미지가 깨지지 않도록 `object-fit: cover` 코드를 추가하였습니다. 
#449
> ProductItem 컴포넌트 UI 수정(#449)

- src/types/myPage.ts
feat/mypage-shipping-api -> dev
- 기존에 올린 PR에서 type 파일이 빠져서 추가하였습니다.
ex) #111
> feat(MypageDashBoard): 빠진 타입 추가 (#423)

- src/components/route/ProtectedRoute.tsx
feat/router-modal-bug -> dev
- 라우터 모달 버튼 클릭 시 모달이 닫히지 않는 버그를 수정하였습니다.
#447
> bug(ProtectedRoute): 라우터 모달 버튼 클릭 버그 수정(#447)

- src/components/product/productlist/CategoryList.tsx
- src/containers/product/ProductSortContainer.tsx
필터링을 적용한 상태에서 새로고침을 했을 때 발생하여 여러 이슈를 수정했습니다. 
**에러1. 디카페인 버튼 활성화한 상태에서 새로고침을 하면 비활성화 상태로 UI가 새로고침 되는 이슈**
- useState로 관리하고 있던 기존 디카페인 상태 데이터를 `쿼리스트링에 저장된 값이 반영`되도록 수정하였습니다. 
**에러2. 필터링 적용한 상태에서 새로고침을 하면 모든 버튼을 비활성화했을 때에 기대하는 데이터가 나오지 않는 이슈**
- useSearchParams로 불러오던 현재 쿼리스트링 주소를 `new URLSearchParams를 통해 실시간으로 가져오도록` 코드를 수정했습니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/8e4a2c85-b100-4f7c-a75d-039baf416c0e
https://github.com/Eurachacha/hanmogeum/assets/117130358/7af8ece4-5e8b-4751-913f-01d23682b091
#392 #430
> 필터링 관련 오류 해결

- src/components/MypageDashBoard/WidgetMyInfo.tsx
- src/components/MypageDashBoard/WidgetShipping.tsx
- src/components/MypageDashBoard/WidgetTodayTea.tsx
- src/components/common/Header.tsx
- src/components/common/Input.tsx
- src/components/contentsTitle/ContentsTitle.tsx
- src/components/itemInput/ItemInput.tsx
- src/components/login/Login.tsx
- src/components/mypage/ContainerHeader..tsx
- src/components/mypage/NavigationMenu.tsx
- src/components/mypage/OrderDetailInfo.tsx
- src/components/mypage/OrderItemContentsText.tsx
- src/containers/mypage/MyOrderDetailContainer.tsx
- src/containers/mypage/MyOrderListContainer.tsx
- src/containers/mypage/MyProfileLoginContainer.tsx
- src/containers/mypage/MyProfileModifyContainer.tsx
feat/mypage-css-> dev
- 기본 폰트를 SUIT -> 프리텐다드로 변함에 따라 굵기를 조정하였습니다.
- 헤더가 상단에 고정되도록 속성을 추가하였습니다.
#465, #464
> design(mypage,header): 헤더 고정, 마이페이지 폰트 수정

- package-lock.json
- package.json
- src/App.tsx
- src/components/common/LoadingSpinner.tsx
- src/containers/mypage/MyOrderListContainer.tsx
feat/mypage-react-query -> dev
- 리액트 쿼리 패키지 추가 후 전역 설정하였습니다.
- suspense 상태 시 돌아갈 로딩스피너 컴포넌트를 추가하였습니다.
- 마이페이지 > 주문 목록 api 요청 시 리액트 쿼리를 사용하도록 수정하였습니다.
#475, #476
> setting(react-query): 로딩 스피너 컴포넌트 추가, 리액트 쿼리 추가, 마이페이지 리액트 쿼리적용 (#475, #476)

- src/apis/services/admin/sellerDataProvider.ts
- src/components/admin/ProductEdit.tsx
> fix(seller): 상품이미지 수정 버그 해결(#481)

- src/components/product/productlist/CategoryList.tsx
상단 카테고리 제목 크기와 텍스트를 수정하였습니다.
#470
> fix(ProductList): 카테고리 상단 제목 변경(#470)

- src/components/admin/OrderEdit.tsx
- src/components/admin/OrderList.tsx
- src/components/admin/ProductList.tsx
> design(seller): 주문관리, 주문상세 페이지 스타일링

- src/App.tsx
- src/components/common/ScrollTop.tsx
feat/scroll-top -> dev
- 페이지 이동 시 최상단으로 이동하도록 했습니다.
> feat(App.tsx): ScrollTop 적용(#420)

- src/components/common/Header.tsx
feat/header-footer-css -> dev
- 이전 스타일 코드 수정 과정에서 발생한 스타일 버그 수정합니다.
ex) #486
> bug(Footer): 헤더 오른쪽이 비어보이는 이슈(#486)

- src/components/product/productlist/CategoryList.tsx
- src/components/product/productlist/ProductItem.tsx
- ex) 로그인/회원가입 버튼 컴포넌트 생성
ex) #111
> 상품 목록 페이지 에러 해결(#494)

- README.md
feat/README -> dev
- README 페이지입니다.
#468
> docs(README): README 초안 작성 (#468)

- src/components/common/Header.tsx
> 버전 1.0.1 메인 머지

- src/components/admin/ProductEdit.tsx
> design(seller): 상품상세및수정 페이지 스타일링(#483)

- src/apis/services/admin/sellerDataProvider.ts
- 상품수정 시 teaType, pack이 문자열로 저장되어 발생한 버그를 수정했습니다.
> fix(seller): teaType, pack을 배열로 저장하도록 수정(#505)

- src/apis/services/admin/sellerDataProvider.ts
새로운 사진 등록이 없는 경우 발생하는 에러를 해결했습니다.
> fix(seller): 상품수정중 file 필드가 없을시 리턴(#508)

- src/components/admin/ProductCreate.tsx
- src/components/admin/ProductEdit.tsx
> fix(seller): 상품등록,상품수정 validate오류 해결(#479)

- src/pages/ErrorPage.tsx
feat/error -> dev
- 에러페이지에서 홈으로 돌아가기 클릭시 히스토리에 남지 않도록 했습니다.
> fix(ErrorPage): 홈으로돌아가기 replace처리(#512)

- src/containers/mypage/MyOrderDetailContainer.tsx
feat/mypage-cart-button -> dev
- 장바구니 버튼 클릭 시 새로고침 해야 헤더가 반영되는 버그를 수정하였습니다.
#502
> bug(mypage): 주문 상세 페이지의 장바구니 버튼클릭 시 헤더반영(#502)

- src/containers/product/ProductSortContainer.tsx
데이터 요청 과정 중 error가 발생할 경우 처리할 코드를 추가했습니다.
#515
> fix(ProductList): error 처리 코드 추가(#515)

- src/containers/mypage/MyOrderDetailContainer.tsx
feat/mypage-cart-button -> dev
- 불필요한 코드를 제거하였습니다.
> chore(mypage): 불필요한 코드 제거

- README.md
- src/containers/mypage/MyOrderDetailContainer.tsx
dev -> main
lint 되지 않은 파일을 수정하였습니다.
> 버전 1.0.2 메인 merge 누락된 PR 추가

- src/containers/orderCheckout/OrderListContainer.tsx
- src/pages/OrderCheckoutPage.tsx
- 장바구니에 상품이 없는 경우 바로구매 시 오류가 나는 현상을 해결했습니다.
- 구매하기 페이지 접근시의 모달깜빡임도 해결했습니다.
#364
> fix(구매하기): 장바구니수량이0일때 바로구매 오류 해결(#524)

- src/Router.tsx
- src/components/route/ProtectedRoute.tsx
- src/containers/mypage/MyProfileModifyContainer.tsx
- src/hooks/useAuthorization.ts
feat/route-bugs -> dev
- 이미 로그인된 사용자 리디렉션 경로 수정
- 모달 확인 버튼 후 새로고침되도록 수정
- 경로 이동시 권한체크 되도록 수정
#500, #523, #526
> bug(router): 라우터 관련 버그 수정(#500, #523, #526)

- src/App.tsx
- src/components/common/LoadingSpinner.tsx
feat/spinner-fix -> dev
- 크기 단위 수정
- contents 최소 높이 수정 
#527
> bug(App): contents min-height 제거 후 높이 수정

- src/App.tsx
- src/components/common/Header.tsx
feat/app-width -> dev
- App의 기본 내용이 있는 컨텐츠 부분 설정을 100%로 설정하였습니다.
- 헤더 width 100%로 설정하였습니다.
#534
> bug(App): 컨텐츠 부분을 기본 100%로 설정(#534)

- src/pages/ProductDetailPage.tsx
- 로딩 및 캐싱을 위해 tanstack-query를 도입했습니다.
> feat(상품상세): 로딩,캐싱 처리를위한 리액트쿼리도입(#541)

- src/components/admin/ProductCreate.tsx
- src/components/admin/ProductEdit.tsx
- 해시태그를 5개이상 등록 시 경고문구 출력이 되지 않는 오류를 해결했습니다.
- 가격과 수량 validation을 수정했습니다.
> fix(seller): 상품등록및수정 validation 오류 해결(#547)

- src/apis/services/admin/sellerDataProvider.ts
- src/components/admin/OrderList.tsx
- src/components/admin/ProductList.tsx
- dataProvider 페이지네이션 코드 추가
- 주문관리 페이지네이션 연결
- 상품관리 페이지네이션 연결
> feat(seller): 상품관리, 주문관리 페이지네이션(#549)

- src/components/admin/OrderEdit.tsx
- src/components/admin/OrderList.tsx
- src/components/admin/ProductList.tsx
- feat/seller -> dev
- 판매관리페이지 정렬기능 구현
> feat(seller): 판매관리페이지 정렬기능 구현(#551)

- src/apis/services/admin/sellerDataProvider.ts
- 상품 이미지 등록 input이 단일 이미지 input으로 바뀌면서 발생한 오류를 해결했습니다.
> fix(seller): 상품 이미지 등록 오류 해결(#557)

- src/apis/services/users.ts
- src/containers/mypage/MyProfileModifyContainer.tsx
feat/mypage-bug -> dev
- 이진 address필드가 하나였을 때 합쳤던 로직을 분리하였습니다.
- 내 정보 변경 후 변경된 정보가 업데이트 되도록 수정하였습니다.
#544, #545
> bug(mypage): 마이페이지 내 정보 수정 페이지 관련 버그 수정(#544, #545)

- .env
- src/App.tsx
- vite.env.d.ts
feat/ReactQueryDevtool -> dev
- 개발 환경에서만 보일 수 있도록 환경변수를 추가하였습니다.
#537
> setting(env): ReactQueryDevtools 개발환경에만 보이도록 수정(#537)

- src/components/admin/ProductEdit.tsx
- 누적판매량을 출력하고 수량 Input의 validation을 추가했습니다.
> feat(seller): 상품수정페이지 누적판매량 출력(#566)

- src/components/product/productlist/ProductItem.tsx
상품목록아이템을 hover하면 해당하는 taste 태그를 보여주는 코드를 추가하였습니다. 
https://github.com/Eurachacha/hanmogeum/assets/117130358/a4b02bf3-ce33-414c-8b7f-b55d7c4d4fd8
#449
> fix(ProductList): 상품목록아이템 hover 시 taste 추가(#449)

- src/components/admin/ProductCreate.tsx
- src/components/admin/ProductEdit.tsx
- src/components/admin/ProductList.tsx
- 상품등록및 수정 시 상품공개여부를 수정 구현
- 상품목록에서 공개여부 열람 가능
> feat(seller): 상품공개여부 수정 구현 및 list출력(#568)

- src/components/admin/OrderList.tsx
- src/components/admin/ProductList.tsx
- 일부필드 sortable설정을 추가했습니다.
- 상품 제목순, id순 정렬이 가능합니다.
> fix(seller): 관리자페이지 list sortable설정 수정(#575)

- src/components/admin/OrderEdit.tsx
> feat(seller): 주문상세페이지 주소,상세주소 사이 공백 추가(#577)

- src/components/admin/OrderEdit.tsx
- src/pages/OrderCheckoutPage.tsx
- 주문정보 저장시 하이픈 제거후 저장하도록 수정했습니다.
> fix(seller): 주문상세 연락처 오토하이픈버그수정(#579)

- src/pages/TeaSurveyResultPage.tsx
추천 페이지 링크 공유하기 작업을 친구와 공유하기 버튼으로 수정했습니다.
#360
> fix(RecommendPage): 추천 페이지 링크공유하기 수정(#360)
